"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_incidents_incidentexportasyncresponse import (
    V3IncidentsIncidentExportAsyncResponse,
    V3IncidentsIncidentExportAsyncResponseTypedDict,
)
from squadcast.types import BaseModel
from typing_extensions import TypedDict


class IncidentsIncidentExportAsyncResponseBodyTypedDict(TypedDict):
    r"""The request has been accepted for processing, but processing has not yet completed."""

    data: V3IncidentsIncidentExportAsyncResponseTypedDict


class IncidentsIncidentExportAsyncResponseBody(BaseModel):
    r"""The request has been accepted for processing, but processing has not yet completed."""

    data: V3IncidentsIncidentExportAsyncResponse
