"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_services_createservicerequest import (
    V3ServicesCreateServiceRequest,
    V3ServicesCreateServiceRequestTypedDict,
)
from .v3_services_serviceresponse import (
    V3ServicesServiceResponse,
    V3ServicesServiceResponseTypedDict,
)
import pydantic
from squadcast.types import BaseModel
from squadcast.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ServicesCreateServiceRequestTypedDict(TypedDict):
    owner_id_param: str
    v3_services_create_service_request: V3ServicesCreateServiceRequestTypedDict


class ServicesCreateServiceRequest(BaseModel):
    owner_id_param: Annotated[
        str,
        pydantic.Field(alias="owner_id"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ]

    v3_services_create_service_request: Annotated[
        V3ServicesCreateServiceRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ServicesCreateServiceResponseTypedDict(TypedDict):
    r"""The request has succeeded and a new resource has been created as a result."""

    data: V3ServicesServiceResponseTypedDict


class ServicesCreateServiceResponse(BaseModel):
    r"""The request has succeeded and a new resource has been created as a result."""

    data: V3ServicesServiceResponse
