"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_teams_teammember import V3TeamsTeamMember, V3TeamsTeamMemberTypedDict
from .v3_teams_teamrole import V3TeamsTeamRole, V3TeamsTeamRoleTypedDict
from pydantic import model_serializer
from squadcast.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OrganizationTypedDict(TypedDict):
    id: str
    name: str
    slug: str


class Organization(BaseModel):
    id: str

    name: str

    slug: str


class V3TeamsTeamResponseTypedDict(TypedDict):
    id: str
    created_at: str
    updated_at: str
    created_by: str
    organization_id: str
    name: str
    description: str
    slug: str
    members: List[V3TeamsTeamMemberTypedDict]
    default: bool
    organization: OrganizationTypedDict
    roles: NotRequired[List[V3TeamsTeamRoleTypedDict]]


class V3TeamsTeamResponse(BaseModel):
    id: str

    created_at: str

    updated_at: str

    created_by: str

    organization_id: str

    name: str

    description: str

    slug: str

    members: List[V3TeamsTeamMember]

    default: bool

    organization: Organization

    roles: Optional[List[V3TeamsTeamRole]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["roles"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
