"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v4_statuspages_issues_liststatuspageissuestatesresponse import (
    V4StatusPagesIssuesListStatusPageIssueStatesResponse,
    V4StatusPagesIssuesListStatusPageIssueStatesResponseTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata
from typing import List
from typing_extensions import Annotated, TypedDict


class IssuesListStatusPageIssueStatesRequestTypedDict(TypedDict):
    statuspage_id: str


class IssuesListStatusPageIssueStatesRequest(BaseModel):
    statuspage_id: Annotated[
        str,
        pydantic.Field(alias="statuspageID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class IssuesListStatusPageIssueStatesResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: List[V4StatusPagesIssuesListStatusPageIssueStatesResponseTypedDict]


class IssuesListStatusPageIssueStatesResponse(BaseModel):
    r"""The request has succeeded."""

    data: List[V4StatusPagesIssuesListStatusPageIssueStatesResponse]
