"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_services_aptaconfigrequest import (
    V3ServicesAPTAConfigRequest,
    V3ServicesAPTAConfigRequestTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ServicesCreateOrUpdateAPTAConfigRequestTypedDict(TypedDict):
    service_id: str
    v3_services_apta_config_request: V3ServicesAPTAConfigRequestTypedDict


class ServicesCreateOrUpdateAPTAConfigRequest(BaseModel):
    service_id: Annotated[
        str,
        pydantic.Field(alias="serviceID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    v3_services_apta_config_request: Annotated[
        V3ServicesAPTAConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ServicesCreateOrUpdateAPTAConfigDataTypedDict(TypedDict):
    msg: str


class ServicesCreateOrUpdateAPTAConfigData(BaseModel):
    msg: str


class ServicesCreateOrUpdateAPTAConfigResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: ServicesCreateOrUpdateAPTAConfigDataTypedDict


class ServicesCreateOrUpdateAPTAConfigResponse(BaseModel):
    r"""The request has succeeded."""

    data: ServicesCreateOrUpdateAPTAConfigData
