"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_services_notificationdelayconfigrequest import (
    V3ServicesNotificationDelayConfigRequest,
    V3ServicesNotificationDelayConfigRequestTypedDict,
)
from .v3_services_serviceresponse import (
    V3ServicesServiceResponse,
    V3ServicesServiceResponseTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ServicesDelayedNotificationConfigRequestTypedDict(TypedDict):
    service_id: str
    v3_services_notification_delay_config_request: (
        V3ServicesNotificationDelayConfigRequestTypedDict
    )


class ServicesDelayedNotificationConfigRequest(BaseModel):
    service_id: Annotated[
        str,
        pydantic.Field(alias="serviceID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    v3_services_notification_delay_config_request: Annotated[
        V3ServicesNotificationDelayConfigRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ServicesDelayedNotificationConfigResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V3ServicesServiceResponseTypedDict


class ServicesDelayedNotificationConfigResponse(BaseModel):
    r"""The request has succeeded."""

    data: V3ServicesServiceResponse
