"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v4_statuspages_updatestatuspagebyidrequest import (
    V4StatusPagesUpdateStatusPageByIDRequest,
    V4StatusPagesUpdateStatusPageByIDRequestTypedDict,
)
from .v4_statuspages_updatestatuspagebyidresponse import (
    V4StatusPagesUpdateStatusPageByIDResponse,
    V4StatusPagesUpdateStatusPageByIDResponseTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class StatusPagesUpdateStatusPageByIDRequestTypedDict(TypedDict):
    statuspage_id: str
    v4_status_pages_update_status_page_by_id_request: (
        V4StatusPagesUpdateStatusPageByIDRequestTypedDict
    )


class StatusPagesUpdateStatusPageByIDRequest(BaseModel):
    statuspage_id: Annotated[
        str,
        pydantic.Field(alias="statuspageID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    v4_status_pages_update_status_page_by_id_request: Annotated[
        V4StatusPagesUpdateStatusPageByIDRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class StatusPagesUpdateStatusPageByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V4StatusPagesUpdateStatusPageByIDResponseTypedDict


class StatusPagesUpdateStatusPageByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V4StatusPagesUpdateStatusPageByIDResponse
