"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_services_taggingrules_taggingruleresponse import (
    V3ServicesTaggingRulesTaggingRuleResponse,
    V3ServicesTaggingRulesTaggingRuleResponseTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata
from typing import List
from typing_extensions import Annotated, TypedDict


class TaggingRulesGetTaggingRulesRequestTypedDict(TypedDict):
    service_id: str


class TaggingRulesGetTaggingRulesRequest(BaseModel):
    service_id: Annotated[
        str,
        pydantic.Field(alias="serviceID"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class TaggingRulesGetTaggingRulesDataTypedDict(TypedDict):
    rules: List[V3ServicesTaggingRulesTaggingRuleResponseTypedDict]


class TaggingRulesGetTaggingRulesData(BaseModel):
    rules: List[V3ServicesTaggingRulesTaggingRuleResponse]


class TaggingRulesGetTaggingRulesResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: TaggingRulesGetTaggingRulesDataTypedDict


class TaggingRulesGetTaggingRulesResponse(BaseModel):
    r"""The request has succeeded."""

    data: TaggingRulesGetTaggingRulesData
