"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_teams_teammemberresponse import (
    V3TeamsTeamMemberResponse,
    V3TeamsTeamMemberResponseTypedDict,
)
from .v3_teams_updateteammemberrequest import (
    V3TeamsUpdateTeamMemberRequest,
    V3TeamsUpdateTeamMemberRequestTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class TeamsUpdateTeamMemberRequestTypedDict(TypedDict):
    team_id: str
    member_id: str
    v3_teams_update_team_member_request: V3TeamsUpdateTeamMemberRequestTypedDict


class TeamsUpdateTeamMemberRequest(BaseModel):
    team_id: Annotated[
        str,
        pydantic.Field(alias="teamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    member_id: Annotated[
        str,
        pydantic.Field(alias="memberId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    v3_teams_update_team_member_request: Annotated[
        V3TeamsUpdateTeamMemberRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class TeamsUpdateTeamMemberResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V3TeamsTeamMemberResponseTypedDict


class TeamsUpdateTeamMemberResponse(BaseModel):
    r"""The request has succeeded."""

    data: V3TeamsTeamMemberResponse
