"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from typing_extensions import TypedDict


class V3IncidentsTagsSnoozeDetailsTypedDict(TypedDict):
    is_snoozed: bool
    start_time: Nullable[datetime]
    end_time: Nullable[datetime]
    total_time_in_mins: int


class V3IncidentsTagsSnoozeDetails(BaseModel):
    is_snoozed: bool

    start_time: Nullable[datetime]

    end_time: Nullable[datetime]

    total_time_in_mins: int

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
