"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class StepTypedDict(TypedDict):
    content: str
    completed: bool
    completed_at: NotRequired[datetime]


class Step(BaseModel):
    content: str

    completed: bool

    completed_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["completed_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3IncidentsRunbooksRunbookResponseTypedDict(TypedDict):
    incident_id: str
    runbook_id: str
    name: str
    steps: List[StepTypedDict]
    id: NotRequired[str]
    deleted: NotRequired[bool]
    deleted_at: NotRequired[datetime]


class V3IncidentsRunbooksRunbookResponse(BaseModel):
    incident_id: str

    runbook_id: str

    name: str

    steps: List[Step]

    id: Optional[str] = None

    deleted: Optional[bool] = None

    deleted_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "deleted", "deleted_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
