"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .common_v3_entityowner import CommonV3EntityOwner, CommonV3EntityOwnerTypedDict
from .v3_runbooks_step import V3RunbooksStep, V3RunbooksStepTypedDict
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class V3RunbooksUpdateRunbookRequestTypedDict(TypedDict):
    r"""Represents the request body for updating a runbook."""

    name: str
    r"""The name of the runbook."""
    steps: List[V3RunbooksStepTypedDict]
    r"""The steps that make up the runbook."""
    entity_owner: NotRequired[CommonV3EntityOwnerTypedDict]
    r"""The owner of the entity."""


class V3RunbooksUpdateRunbookRequest(BaseModel):
    r"""Represents the request body for updating a runbook."""

    name: str
    r"""The name of the runbook."""

    steps: List[V3RunbooksStep]
    r"""The steps that make up the runbook."""

    entity_owner: Optional[CommonV3EntityOwner] = None
    r"""The owner of the entity."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["entity_owner"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
