"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_slo_slo import V3SloSlo, V3SloSloTypedDict
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InsightsTypedDict(TypedDict):
    error_budget_consumption_for_past_30days: int


class Insights(BaseModel):
    error_budget_consumption_for_past_30days: int


class V3SLOSLOWithInsightsResponseTypedDict(TypedDict):
    slo: V3SloSloTypedDict
    insights: NotRequired[InsightsTypedDict]


class V3SLOSLOWithInsightsResponse(BaseModel):
    slo: V3SloSlo

    insights: Optional[Insights] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["insights"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
