"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_services_routingrules_expressionbranch import (
    V3ServicesRoutingRulesExpressionBranch,
    V3ServicesRoutingRulesExpressionBranchTypedDict,
)
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


V3ServicesRoutingRulesRoutingRuleEntityType = Literal[
    "user",
    "squad",
    "escalation_policy",
]


class V3ServicesRoutingRulesRoutingRuleRouteToTypedDict(TypedDict):
    entity_type: V3ServicesRoutingRulesRoutingRuleEntityType
    entity_id: str


class V3ServicesRoutingRulesRoutingRuleRouteTo(BaseModel):
    entity_type: V3ServicesRoutingRulesRoutingRuleEntityType

    entity_id: str


class V3ServicesRoutingRulesRoutingRuleTypedDict(TypedDict):
    expression: str
    route_to: V3ServicesRoutingRulesRoutingRuleRouteToTypedDict
    is_basic: bool
    basic_expression: NotRequired[List[V3ServicesRoutingRulesExpressionBranchTypedDict]]


class V3ServicesRoutingRulesRoutingRule(BaseModel):
    expression: str

    route_to: V3ServicesRoutingRulesRoutingRuleRouteTo

    is_basic: bool

    basic_expression: Optional[List[V3ServicesRoutingRulesExpressionBranch]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["basic_expression"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
