"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class V3TeamsUpdateTeamRequestMemberTypedDict(TypedDict):
    user_id: str
    role_ids: List[str]
    r"""this field is required if you are using RBAC permission model"""
    role: NotRequired[str]
    r"""this field is required if you are using OBAC permission model"""


class V3TeamsUpdateTeamRequestMember(BaseModel):
    user_id: str

    role_ids: List[str]
    r"""this field is required if you are using RBAC permission model"""

    role: Optional[str] = None
    r"""this field is required if you are using OBAC permission model"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["role"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3TeamsUpdateTeamRequestTypedDict(TypedDict):
    members: List[V3TeamsUpdateTeamRequestMemberTypedDict]
    name: NotRequired[str]
    description: NotRequired[str]


class V3TeamsUpdateTeamRequest(BaseModel):
    members: List[V3TeamsUpdateTeamRequestMember]

    name: Optional[str] = None

    description: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
