"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_workflows_communicationchannel import (
    V3WorkflowsCommunicationChannel,
    V3WorkflowsCommunicationChannelTypedDict,
)
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


V3WorkflowsSqAddCommunicationChannelUpdateName = Literal[
    "sq_add_communication_channel",
]


class V3WorkflowsSqAddCommunicationChannelUpdateDataTypedDict(TypedDict):
    channels: NotRequired[List[V3WorkflowsCommunicationChannelTypedDict]]


class V3WorkflowsSqAddCommunicationChannelUpdateData(BaseModel):
    channels: Optional[List[V3WorkflowsCommunicationChannel]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channels"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3WorkflowsSqAddCommunicationChannelUpdateTypedDict(TypedDict):
    name: V3WorkflowsSqAddCommunicationChannelUpdateName
    data: NotRequired[V3WorkflowsSqAddCommunicationChannelUpdateDataTypedDict]


class V3WorkflowsSqAddCommunicationChannelUpdate(BaseModel):
    name: V3WorkflowsSqAddCommunicationChannelUpdateName

    data: Optional[V3WorkflowsSqAddCommunicationChannelUpdateData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
