"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


Condition = Literal[
    "and",
    "or",
]


class V3WorkflowsWorkflowFiltersTypedDict(TypedDict):
    type: NotRequired[str]
    key: NotRequired[str]
    value: NotRequired[str]
    condition: NotRequired[Condition]
    filters: NotRequired[List[V3WorkflowsWorkflowFiltersTypedDict]]


class V3WorkflowsWorkflowFilters(BaseModel):
    type: Optional[str] = None

    key: Optional[str] = None

    value: Optional[str] = None

    condition: Optional[Condition] = None

    filters: Optional[List[V3WorkflowsWorkflowFilters]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "key", "value", "condition", "filters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
