"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


V3WorkflowsSqSendEmailUpdateName = Literal["sq_send_email",]


class V3WorkflowsSqSendEmailUpdateDataTypedDict(TypedDict):
    to: NotRequired[List[str]]
    subject: NotRequired[str]
    body: NotRequired[str]


class V3WorkflowsSqSendEmailUpdateData(BaseModel):
    to: Optional[List[str]] = None

    subject: Optional[str] = None

    body: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["to", "subject", "body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3WorkflowsSqSendEmailUpdateTypedDict(TypedDict):
    name: V3WorkflowsSqSendEmailUpdateName
    data: NotRequired[V3WorkflowsSqSendEmailUpdateDataTypedDict]


class V3WorkflowsSqSendEmailUpdate(BaseModel):
    name: V3WorkflowsSqSendEmailUpdateName

    data: Optional[V3WorkflowsSqSendEmailUpdateData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
