"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


V3WorkflowsMsTeamsMessageUserUpdateName = Literal["msteams_message_user",]


class V3WorkflowsMsTeamsMessageUserUpdateDataTypedDict(TypedDict):
    member_id: NotRequired[str]
    message: NotRequired[str]


class V3WorkflowsMsTeamsMessageUserUpdateData(BaseModel):
    member_id: Optional[str] = None

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["member_id", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3WorkflowsMsTeamsMessageUserUpdateTypedDict(TypedDict):
    name: V3WorkflowsMsTeamsMessageUserUpdateName
    data: NotRequired[V3WorkflowsMsTeamsMessageUserUpdateDataTypedDict]


class V3WorkflowsMsTeamsMessageUserUpdate(BaseModel):
    name: V3WorkflowsMsTeamsMessageUserUpdateName

    data: Optional[V3WorkflowsMsTeamsMessageUserUpdateData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
