"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


V3WorkflowsSqTriggerManualWebhookUpdateName = Literal["sq_trigger_manual_webhook",]


class V3WorkflowsSqTriggerManualWebhookUpdateDataTypedDict(TypedDict):
    id: NotRequired[str]


class V3WorkflowsSqTriggerManualWebhookUpdateData(BaseModel):
    id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class V3WorkflowsSqTriggerManualWebhookUpdateTypedDict(TypedDict):
    name: V3WorkflowsSqTriggerManualWebhookUpdateName
    data: NotRequired[V3WorkflowsSqTriggerManualWebhookUpdateDataTypedDict]


class V3WorkflowsSqTriggerManualWebhookUpdate(BaseModel):
    name: V3WorkflowsSqTriggerManualWebhookUpdateName

    data: Optional[V3WorkflowsSqTriggerManualWebhookUpdateData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
