"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from squadcast_sdk.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class V4StatusPagesComponentGroupsGetComponentGroupByIDResponseTypedDict(TypedDict):
    id: int
    page_id: int
    name: str
    allow_subscription: bool
    description: NotRequired[str]


class V4StatusPagesComponentGroupsGetComponentGroupByIDResponse(BaseModel):
    id: int

    page_id: Annotated[int, pydantic.Field(alias="pageID")]

    name: str

    allow_subscription: Annotated[bool, pydantic.Field(alias="allowSubscription")]

    description: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    V4StatusPagesComponentGroupsGetComponentGroupByIDResponse.model_rebuild()
except NameError:
    pass
