"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v3_webforms_webformresponse import (
    V3WebformsWebformResponse,
    V3WebformsWebformResponseTypedDict,
)
import pydantic
from squadcast_sdk.types import BaseModel
from squadcast_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class WebformsGetWebformByIDRequestTypedDict(TypedDict):
    webform_id: int
    owner_id: str


class WebformsGetWebformByIDRequest(BaseModel):
    webform_id: Annotated[
        int,
        pydantic.Field(alias="webformId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    owner_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=False))
    ]


class WebformsGetWebformByIDResponseTypedDict(TypedDict):
    r"""The request has succeeded."""

    data: V3WebformsWebformResponseTypedDict


class WebformsGetWebformByIDResponse(BaseModel):
    r"""The request has succeeded."""

    data: V3WebformsWebformResponse
